-- 코드를 입력하세요
SELECT YEAR(SUB.SALES_DATE) AS YEAR, MONTH(SUB.SALES_DATE) AS MONTH, SUB.GENDER AS GENDER, COUNT(DISTINCT SUB.USER_ID) AS USERS
FROM(SELECT SALES_DATE, GENDER, SALES_AMOUNT, USER_INFO.USER_ID
FROM ONLINE_SALE 
INNER JOIN USER_INFO 
ON USER_INFO.USER_ID = ONLINE_SALE.USER_ID) AS SUB
GROUP BY YEAR(SUB.SALES_DATE), MONTH(SUB.SALES_DATE), SUB.GENDER
HAVING SUB.GENDER IS NOT NULL
ORDER BY YEAR(SUB.SALES_DATE), MONTH(SUB.SALES_DATE), SUB.GENDER 

# SELECT * FROM  ONLINE_SALE 
# INNER JOIN USER_INFO ON USER_INFO.USER_ID = ONLINE_SALE.USER_ID